#!/bin/sh

set -e

lb config noauto \
	-d "buster" \
	--architectures "amd64" \
	--debian-installer "live" \
	--debian-installer-gui true \
	--memtest none \
	--win32-loader false \
	--initsystem "runit" \
	--archive-areas "main contrib non-free" \
	--linux-packages "linux-image" \
	"${@}"
